# ===============================
# Docker Compose (Vaultwarden)
# ===============================
# host: http://localhost:8000
# username:
# password:

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    ports:
      - "127.0.0.1:8000:80"
    restart: unless-stopped
    environment:
      DOMAIN: "http://localhost:8000"
    volumes:
      - vaultwarden-data:/data

volumes:
  vaultwarden-data: