# ===============================
# Docker Compose (Vikunja)
# ===============================
# host: http://localhost:3456
# username:
# password:

services:
  vikunja:
    image: vikunja/vikunja:latest
    container_name: vikunja
    ports:
      - "3456:3456"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      VIKUNJA_SERVICE_PUBLICURL: http://localhost:3456
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_PASSWORD: changeme
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: change_this_to_a_long_random_secret
    volumes:
      - vikunja-files:/app/vikunja/files

  db:
    image: postgres:16
    container_name: vikunja-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vikunja
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: vikunja
    volumes:
      - vikunja-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -h localhost -U vikunja"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  vikunja-files:
  vikunja-db: