# ===============================
# Docker Compose (Tiny Tiny RSS)
# ===============================
# host: http://localhost:8280
# username: admin
# password: password

services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

    volumes:
      - ttrss_db:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ghcr.io/tt-rss/tt-rss:latest
    restart: unless-stopped

    environment:
      TTRSS_DB_HOST: db
      TTRSS_DB_USER: postgres
      TTRSS_DB_PASS: password
      TTRSS_DB_NAME: postgres
      TTRSS_SELF_URL_PATH: http://localhost:8280

    volumes:
      - ttrss_app:/var/www/html

    depends_on:
      db:
        condition: service_healthy

  updater:
    image: ghcr.io/tt-rss/tt-rss:latest
    restart: unless-stopped

    command: /opt/tt-rss/updater.sh

    environment:
      TTRSS_DB_HOST: db
      TTRSS_DB_USER: postgres
      TTRSS_DB_PASS: password
      TTRSS_DB_NAME: postgres

    volumes:
      - ttrss_app:/var/www/html

    depends_on:
      - app

  web-nginx:
    image: ghcr.io/tt-rss/tt-rss-web-nginx:latest
    restart: unless-stopped

    ports:
      - "127.0.0.1:8280:80"

    volumes:
      - ttrss_app:/var/www/html:ro

    depends_on:
      - app

volumes:
  ttrss_db:
  ttrss_app: