# ===============================
# Docker Compose (TiddlyWiki)
# ===============================
# host: http://localhost:8280
# username:
# password:

services:
  tiddlywiki:
    image: jbardi/tiddlywiki5-lazy-images:latest
    container_name: tiddlywiki
    restart: unless-stopped

    ports:
      - "8280:8080"

    environment:
      TZ: America/Denver

    volumes:
      - tiddlywiki_data:/var/lib/tiddlywiki

volumes:
  tiddlywiki_data: