# ===============================
# Docker Compose (Papra)
# ===============================
# host: http://localhost:1221
# username:
# password:

services:
  papra:
    image: ghcr.io/papra-hq/papra:latest
    restart: unless-stopped
    ports:
      - "1221:1221"
    environment:
      APP_BASE_URL: http://localhost:1221
    user: "1000:1000"
    volumes:
      - papra_data:/app/app-data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:1221"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  papra_data: