# ===============================
# Docker Compose (rclone-config)
# ===============================
# host:
# username:
# password:

services:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone-config
    command: ["config"]
    volumes:
      - rclone_config:/config/rclone
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  rclone_config: