services:
  chiyogami:
    image: ghcr.io/rhee876527/chiyogami:latest
    container_name: chiyogami
    restart: unless-stopped

    ports:
      - "127.0.0.1:8000:8000"

    volumes:
      - ./pastes:/pastes