# ===============================
# Docker Compose (MySpeed)
# ===============================
# host: http://localhost:5216
# username:
# password:

services:
  myspeed:
    image: germannewsmaker/myspeed:latest
    container_name: myspeed
    restart: unless-stopped
    ports:
      - "5216:5216"
    volumes:
      - myspeed_data:/myspeed/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:5216/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  myspeed_data: