services:
  just-short-it:
    container_name: JustShortIt
    image: miawinter/just-short-it:latest
    ports:
      - "80:8080"
    environment:
      - "JSI_BaseUrl="
      - "JSI_Account__Username="
      - "JSI_Account__Password="
      - "JSI_Redis__ConnectionString=redis,password="
    depends_on:
      - redis
  redis:
    container_name: Redis
    image: redis:alpine
    environment:
      - "REDIS_PASSWORD="
    volumes:
      - ./redis:/data