# ===============================
# Docker Compose (Syncthing)
# ===============================
# host: http://localhost:8384
# username:
# password:

services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    hostname: syncthing
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    environment:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - syncthing_data:/var/syncthing
    healthcheck:
      test: ["CMD","curl","-fkLsS","-m","2","http://localhost:8384/rest/noauth/health"]
      interval: 60s
      timeout: 10s
      retries: 3

volumes:
  syncthing_data: