version: '3'
services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: snapdrop
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/config
    restart: unless-stopped
