# ===============================
# Docker Compose (iSponsorBlockTV)
# ===============================
# host: http://localhost:5000
# username:
# password:

services:
  isponsorblocktv:
    image: ghcr.io/dmunozv04/isponsorblocktv:latest
    container_name: isponsorblocktv
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - isponsorblocktv_data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  isponsorblocktv_data: