# ===============================
# Docker Compose (Syncloud)
# ===============================
# host: https://localhost
# username:
# password:

services:
  syncloud:
    image: syncloud/platform-bookworm-amd64:25.09
    container_name: syncloud
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - syncloud_storage:/opt/disk/internal
    healthcheck:
      test: ["CMD","wget","--spider","-q","https://localhost"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  syncloud_storage: