# ===============================
# Docker Compose (Docker Volume Backup)
# ===============================

services:
  volume-consumer:
    build:
      context: ./my-app
    container_name: my-app
    restart: unless-stopped
    volumes:
      - app_data:/var/my-app
    labels:
      docker-volume-backup.stop-during-backup: "true"

  backup:
    image: offen/docker-volume-backup:v2
    container_name: volume-backup
    restart: unless-stopped
    environment:
      BACKUP_CRON_EXPRESSION: "0 3 * * *"   # daily at 03:00
      BACKUP_FILENAME: "backup-%Y-%m-%dT%H-%M-%S.tar.gz"
      BACKUP_RETENTION_DAYS: "7"
      BACKUP_PRUNING_LEEWAY: "1"
      COMPRESSION_LEVEL: "6"
      LOG_LEVEL: "info"
    volumes:
      - app_data:/backup/my-app-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - volume_backup_archive:/archive

volumes:
  app_data:
  volume_backup_archive:
