# ===============================
# Docker Compose (Pepperminty Wiki)
# ===============================
# host: http://localhost:8080
# username:
# password:

services:
  pepperminty:
    image: pepperlabs/pepperminty-wiki:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - pepperminty_config:/srv/app
      - pepperminty_data:/srv/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  pepperminty_config:
  pepperminty_data: