# ===============================
# Docker Compose (SSHwifty)
# ===============================
# host: http://localhost:8182
# username:
# password:

services:
  sshwifty:
    image: niruix/sshwifty:latest
    container_name: sshwifty
    restart: unless-stopped
    ports:
      - "8182:8182"
    healthcheck:
      test: ["CMD","wget","--spider","-q","http://localhost:8182"]
      interval: 30s
      timeout: 5s
      retries: 5